# Generated by Django 3.0.3 on 2020-05-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200502_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_name', models.ManyToManyField(to='catalog.A')),
            ],
        ),
    ]
